### ISSUE TITLE
Notification glitch with someone favouriting an ended poll of mine

### ISSUE THREAD

**Issue by llamacucumber** [ronilaukkarinen/mastodon-bird-ui#19] opened 2023-04-11 13:23 UTC
This is pretty edge-case.
It can be reproduced by starting a poll and then having someone favourite after it ends.

<img width="607" alt="image" src="https://user-images.githubusercontent.com/18673584/231176121-b3f2e6ee-4844-4bc4-a3b8-60e6f42d5cd2.png">

**Comment by llamacucumber** [comment] 2023-04-11 20:11
Another notification glitch triggered by user signup
<img width="602" alt="image" src="https://user-images.githubusercontent.com/18673584/231277560-05ac897e-cc5d-4461-acec-e229d81a2c11.png">

**Comment by ronilaukkarinen** [comment] 2023-04-12 12:43
@llamacucumber Can you share the HTML code of these two notifications? I don't have sign ups enabled on my instance. I have a dev environment of course, but it's easiest to hack to HTML directly.

**Comment by ronilaukkarinen** [comment] 2023-04-13 17:38
I have now tested these on my test instance.

![image](https://user-images.githubusercontent.com/1534150/231839974-b39c0335-46da-47ff-b6b7-569f0e082ac4.png)
![image](https://user-images.githubusercontent.com/1534150/231840162-c60dc09a-2a0c-415c-825a-d6d821662615.png)

Are you sure you are using the latest version (1.4.7) and latest Mastodon (4.1.2)? @llamacucumber 

Can't reproduce so I'm closing this issue.

**Comment by ronilaukkarinen** [comment] 2023-04-13 17:41
![image](https://user-images.githubusercontent.com/1534150/231840863-b593ab9e-c765-4f0c-91b0-90ceb3e680c0.png)

**Comment by llamacucumber** [comment] 2023-04-13 20:27
`<article aria-posinset="2" aria-setsize="40" data-id="58079" tabindex="0"><div tabindex="-1"><div class="notification notification-admin-sign-up focusable" tabindex="0" aria-label="RiversideBryan signed up, Apr 13 at 04:07 PM"><div class="notification__message"><div class="notification__favourite-icon-wrapper"><i class="fa fa-user-plus fa-fw"></i></div><span title="2023-04-13T20:07:06.438Z"><span><bdi><a class="notification__display-name" href="/@RiversideBryan" title="RiversideBryan">Bryan <img draggable="false" class="emojione" alt="🏳️‍🌈" title=":rainbow-flag:" src="/emoji/1f3f3-fe0f-200d-1f308.svg"></a></bdi> signed up</span></span></div><div class="account"><div class="account__wrapper"><a class="account__display-name" title="RiversideBryan" href="/@RiversideBryan"><div class="account__avatar-wrapper"><div class="account__avatar" style="width: 46px; height: 46px;"><img src="https://sfo3.digitaloceanspaces.com/veganism-space/accounts/avatars/110/193/305/547/782/582/original/c40ec41abdeaef30.jpeg" alt="RiversideBryan"></div></div><div><span class="display-name"><bdi><strong class="display-name__html">Bryan <img draggable="false" class="emojione" alt="🏳️‍🌈" title=":rainbow-flag:" src="/emoji/1f3f3-fe0f-200d-1f308.svg"></strong></bdi> <span class="display-name__account">@RiversideBryan</span></span><span><strong><span>1</span></strong> Follower</span>  </div></a><div class="account__relationship"><button type="button" aria-label="Unfollow" aria-hidden="false" title="Unfollow" class="icon-button active" tabindex="0" style="font-size: 18px; width: 23.142857px; height: 23.142857px; line-height: 18px;"><i class="fa fa-user-times fa-fw" aria-hidden="true"></i> </button></div></div></div></div></div></article>`

<img width="599" alt="image" src="https://user-images.githubusercontent.com/18673584/231875426-6ad0bc7c-8dd3-4747-b49d-b67f7b203bb2.png">

**Comment by llamacucumber** [comment] 2023-04-13 20:28
And I am using 1.4.7 and 4.1.2

**Comment by ronilaukkarinen** [comment] 2023-04-14 07:26
> <img alt="image" width="599" src="https://user-images.githubusercontent.com/18673584/231875426-6ad0bc7c-8dd3-4747-b49d-b67f7b203bb2.png">

This should be fixed now in 1.4.8rc1. Can you test it?

**Closed** 2023-04-14 07:25 UTC
Labels: bug, help wanted, can't reproduce
