### ISSUE TITLE
Issue with "More" button's hover highlight on selected post on Advanced Interface 

### ISSUE THREAD

**Issue by onekopaka** [ronilaukkarinen/mastodon-bird-ui#108] opened 2024-02-14 07:20 UTC
In Mastodon Bird UI 1.8.5 (tested 1.8.4, 1.8.3 too), with single and mutli-column installed by custom CSS on top of my Mastodon 4.2.5 install, I'm seeing a misaligned hover effect on the "More" button, on a post selected in the "detail" column on the advanced interface.

![image](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/29023/b61b823c-4e81-44e8-b34c-ce0cd2cc5ac4)

The URL I am on in the screenshot above is https://masto.theoks.net/deck/@rolle@mementomori.social/111923023470450677. All the other action buttons both on the selected post and other posts in lists seem to have correct hover effects.
The screenshot is in Firefox on Linux, but I did double check on Chrome, and it appears the same there.

Let me know if there's anything I can do to help figure the issue out, and thanks in advance!

**Comment by ronilaukkarinen** [comment] 2024-02-14 10:21
These are sometimes pretty hard to fix because of the relation limitations of the Mastodon core HTML. I could make this different to multiple columns CSS. Pull requests always appreciated.

**Comment by ronilaukkarinen** [comment] 2024-04-06 14:06
Can't reproduce this on stable + mstdn.social 4.2.8 or nightly + mementomori.social 4.3.0-alpha. Closing as wontfix/minor at this time.

**Closed by ronilaukkarinen** 2024-04-06 14:06 UTC
Labels: help wanted, low priority, advanced web interface
