### ISSUE TITLE
Verified links display on two lines

### ISSUE THREAD

**Issue by richarvey** [ronilaukkarinen/mastodon-bird-ui#120] opened 2024-05-06 20:45 UTC
When a link is verified it seems to split over two lines in the profile page, one line showing the tick the second the URL. This may be by design but personally I think it would look better on one line. Example of how it displays below:

![Screenshot from 2024-05-06 21-41-27](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/532137/648eb2c4-2735-4e93-a750-755078b7524a)

Mastodon Version: 4.2.8
Version installed 1.8.5
Installation Method: Custom CSS - both style sheets installed

**Comment by ronilaukkarinen** [comment] 2024-05-07 07:38
I don't see that. Do you use old Firefox or some obscure browser? Only newest browsers supported, see #61. Looks like your CSS might be broken in some point (ref #107), can you just copy paste everything to a CSS validator and catch errors?

How it looks like for me:
![image](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1534150/c735219d-0862-42a5-9baf-853d56b77f75)

Can't reproduce, so closing for now. Feel free to send more details.

**Closed by ronilaukkarinen** 2024-05-07 07:38 UTC
