### ISSUE TITLE
Scrolling is glitchy on Safari/webkit

### ISSUE THREAD

**Issue by nanos** [ronilaukkarinen/mastodon-bird-ui#8] opened 2023-04-05 06:31 UTC
This has happened to me since I switched to bird ui. See https://imgur.com/a/Lz4W0kG .

Usually it's just a little jumpy as seen around the 4 second mark - this happens almost every time I scroll more than a few lines at a time. But every now and again, it goes totally bananas, as shown at the end.

Do you have any idea what could cause this?

(This is in Safari on macOS, by the way)

**Comment by ronilaukkarinen** [comment] 2023-04-05 09:22
Thanks for the issue. Safari is a bit tricky, but it should honor the original CSS from the default Mastodon UI.

Can't reproduce this on my MacBook Pro Safari, I don't have an iPhone or iPad to test with. Mastodon core adds the fixed height when it's loading new posts, you can see it on mastodon.social as well:

![Screen-Shot-2023-04-05-12-17-20](https://user-images.githubusercontent.com/1534150/230038110-cf2f3df7-76b2-4bbe-9bb5-a43490cbb540.png)

However, on Mastodon.social the column links are in the right instead of in the bottom and that may prevent it.

Mastodon Bird UI honors the original sticky layout and doesn't intefere with it, the behaviour was fixed in [here](https://github.com/ronilaukkarinen/mastodon-bird-ui/issues/1). There should be not much changes other than the bottom bar.

Does the jankiness happen when you scroll more slowly?

I have no idea what causes this. I'm open to ideas.

**Comment by nanos** [comment] 2023-04-05 09:46
> Thanks for the issue. Safari is a bit tricky,

Understatement of the century 😂 

Yes, I did notice that the same fixed heights are present on mastodon core, without causing that jumping. I will look into it further, to see if I can find out what's causing this.

Yes, the jumping happens when scrolling slowly too. It's not 100% reproducible, but it does happen frequently for me.

Strange stuff ...

**Comment by ronilaukkarinen** [comment] 2023-04-05 16:40
This is just a hunch, but I suggest this offset [here](https://github.com/ronilaukkarinen/mastodon-bird-ui/commit/f8b5ec21535d9356e089c0dc9ba4b04c09ec1fa9) causes it. I added that margin-bottom: -1px to play it safe to prevent double borders in certain situations. I just noticed it might tilt the feed off if all the threads have it. I can't be sure though. Let me know if it fixies it @nanos!

**Comment by nanos** [comment] 2023-04-05 19:45
Nope. Sadly that hasn’t helped 😔

**Comment by nanos** [comment] 2023-04-05 19:55
Ooof, if Safari's dev tools weren't so terrible, I might even be able to figure out what's going on there, but their dev tools are the worst since IE ...

**Comment by nanos** [comment] 2023-04-06 07:44
So, I've been able to narrow it down somewhat. Here is a sample post from my timeline, where this reproducibly happens:

<img width="690" alt="image" src="https://user-images.githubusercontent.com/5182595/230308128-4cb7db53-9e3e-415c-a648-26860ba4a8c1.png">

As you can see, this post is 757px high.

As I scroll down, Mastodon removes the child DOM nodes, and replaces them with plain text, while fixing the height of the wrapping `<article>` node. I assume it does that to prevent memory leaks. I know that this has nothing as such to do with Bird UI, but what happens here, is that the height of the new fixed container is now shorter - only 251px (sorry for the blurring, but I'm not sure how confidential I should keep those post IDs):

<img width="1553" alt="image" src="https://user-images.githubusercontent.com/5182595/230308748-8e0c162d-3f17-4805-90ee-93308c4610fe.png">

The interesting question, of course, is 'Why?' and why only on Safari? Makes no sense to me. 

But that's how far I've gotten today ...

**Comment by nanos** [comment] 2023-04-06 07:50
Actually, interestingly enough, with this specific post I can reproduce this even in Chrome.

**Comment by ronilaukkarinen** [comment] 2023-04-06 08:07
Thanks for testing @nanos! Can you link to that post (if possible) so I can test too this evening? Have you tried the same posts in the original Mastodon and it doesn't happen there on Safari?

**Comment by nanos** [comment] 2023-04-06 08:12
This is the link to the post: https://social.tourmentine.com/objects/8a2bc7ad-8c6e-4994-b2b4-b503fe18a867

However, this only happens on a timeline, so you'd need to get that post into your timeline somehow, and then scroll to find it.

**Comment by NoaHimesaka1873** [comment] 2023-04-21 02:32
Scrolling issue also happens on GNOME Web, which also uses WebKit, so it seems like it's WebKit issue rather than Safari issue.

**Comment by ronilaukkarinen** [comment] 2023-04-22 11:47
It's frustrating, because I haven't been able to reproduce this properly on Gnome Web or Safari. On Chrome not even the slightest (Windows 11, Pop_OS Linux). Have to test it more when I have time. All contribution to this welcome as I'm kinda hopeless right now with this.

**Comment by nanos** [comment] 2023-04-22 11:50
It’s totally weird. I’ve spent a significant amount of time trying to find the cause, but haven’t been able to, beyond what I already wrote above. 

I can’t make sense of it at the moment, and have removed bird ui again, because I can’t get it to work.

**Comment by ronilaukkarinen** [comment] 2023-04-22 12:33
Yeah. I'll try to look at it again in some point. But since I'm using Chrome as main browser and it does work perfectly there for me, I won't be putting much effor to this right now. I'm all open to ideas and if anyone is eager to test out, I really appreciate it. Will leave this issue open until it's resolved.

**Comment by ronilaukkarinen** [comment] 2024-02-09 18:55
Can't reproduce this, I guess it's gone by now. Nevertheless, can't really work on this right now so closing the issue. Feel free to re-comment and re-open if you wish.

**Closed by ronilaukkarinen** 2024-02-09 18:55 UTC
Labels: help wanted, can't reproduce, low priority
